name: docker-ci

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - "master"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: go-task-mgr

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: ghcr.io/pacholoamit/developer-portfolio
            context: .

    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          labels: |
            org.opencontainers.image.title=developer-portfolio
            org.opencontainers.image.description=Developer portfolio forked from someone else and modified to my liking
            org.opencontainers.image.vendor=Pacholo Amit
            org.opencontainers.image.licenses=MIT
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
          flavor: |
            latest=true
          images: ${{ matrix.image }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
